import type { NextPage } from "next";
import Head from "next/head";

const PrivacyPolicyPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col">
        <h1>Privacy Policy</h1>
      </main>
    </>
  );
};

export default PrivacyPolicyPage;
